title: "ZVirox Tech Blog"
description: "Technology, IT, Networking and Cybersecurity tutorials and guides."
url: "https://zvirox.in"

theme: minima

author: "ZVirox"

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown

permalink: /:categories/:title/
