title: "Zvirox"
description: "Technology, IT, Networking and Cybersecurity tutorials and guides."
url: "https://zvirox.in"


author: "Zvirox"

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown

permalink: /:categories/:title/
